-- 코멘트 테이블
CREATE TABLE comments (
     id         BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT
    ,user_id    BIGINT UNSIGNED NOT NULL
    ,post_id    BIGINT UNSIGNED NOT NULL
    ,content    VARCHAR(100) NOT NULL
    ,reply_id   BIGINT UNSIGNED NOT NULL DEFAULT 0
    ,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
    ,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP()
    ,deleted_at DATETIME
);